# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import booksage_pb2 as booksage_dot_v1_dot_booksage__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in booksage/v1/booksage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentParserServiceStub(object):
    """DocumentParserService handles the parsing of complex documents (PDF, EPUB, etc.)
    into structured markdown texts and metadata.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Parse = channel.stream_unary(
                '/booksage.v1.DocumentParserService/Parse',
                request_serializer=booksage_dot_v1_dot_booksage__pb2.ParseRequest.SerializeToString,
                response_deserializer=booksage_dot_v1_dot_booksage__pb2.ParseResponse.FromString,
                _registered_method=True)


class DocumentParserServiceServicer(object):
    """DocumentParserService handles the parsing of complex documents (PDF, EPUB, etc.)
    into structured markdown texts and metadata.
    """

    def Parse(self, request_iterator, context):
        """Parse accepts a stream of binary chunks from a document, and returns
        the extracted metadata and markdown text chunks asynchronously.
        Using client streaming to avoid hitting gRPC maximum message size (4MB limit).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Parse': grpc.stream_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=booksage_dot_v1_dot_booksage__pb2.ParseRequest.FromString,
                    response_serializer=booksage_dot_v1_dot_booksage__pb2.ParseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booksage.v1.DocumentParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booksage.v1.DocumentParserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentParserService(object):
    """DocumentParserService handles the parsing of complex documents (PDF, EPUB, etc.)
    into structured markdown texts and metadata.
    """

    @staticmethod
    def Parse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/booksage.v1.DocumentParserService/Parse',
            booksage_dot_v1_dot_booksage__pb2.ParseRequest.SerializeToString,
            booksage_dot_v1_dot_booksage__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EmbeddingServiceStub(object):
    """EmbeddingService handles text embedding operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateEmbeddings = channel.unary_unary(
                '/booksage.v1.EmbeddingService/GenerateEmbeddings',
                request_serializer=booksage_dot_v1_dot_booksage__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=booksage_dot_v1_dot_booksage__pb2.EmbeddingResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """EmbeddingService handles text embedding operations.
    """

    def GenerateEmbeddings(self, request, context):
        """GenerateEmbeddings accepts batches of text and returns their vector representations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbeddings,
                    request_deserializer=booksage_dot_v1_dot_booksage__pb2.EmbeddingRequest.FromString,
                    response_serializer=booksage_dot_v1_dot_booksage__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booksage.v1.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booksage.v1.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """EmbeddingService handles text embedding operations.
    """

    @staticmethod
    def GenerateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booksage.v1.EmbeddingService/GenerateEmbeddings',
            booksage_dot_v1_dot_booksage__pb2.EmbeddingRequest.SerializeToString,
            booksage_dot_v1_dot_booksage__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
