run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

issues:
  exclude-dirs:
    - internal/pb
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
