// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: booksage/v1/booksage.proto

package booksagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentParserService_Parse_FullMethodName = "/booksage.v1.DocumentParserService/Parse"
)

// DocumentParserServiceClient is the client API for DocumentParserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DocumentParserService handles the parsing of complex documents (PDF, EPUB, etc.)
// into structured markdown texts and metadata.
type DocumentParserServiceClient interface {
	// Parse accepts a stream of binary chunks from a document, and returns
	// the extracted metadata and markdown text chunks asynchronously.
	// Using client streaming to avoid hitting gRPC maximum message size (4MB limit).
	// Using server streaming to handle large parsed outputs incrementally.
	Parse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ParseRequest, ParseResponse], error)
}

type documentParserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentParserServiceClient(cc grpc.ClientConnInterface) DocumentParserServiceClient {
	return &documentParserServiceClient{cc}
}

func (c *documentParserServiceClient) Parse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ParseRequest, ParseResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentParserService_ServiceDesc.Streams[0], DocumentParserService_Parse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ParseRequest, ParseResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentParserService_ParseClient = grpc.BidiStreamingClient[ParseRequest, ParseResponse]

// DocumentParserServiceServer is the server API for DocumentParserService service.
// All implementations must embed UnimplementedDocumentParserServiceServer
// for forward compatibility.
//
// DocumentParserService handles the parsing of complex documents (PDF, EPUB, etc.)
// into structured markdown texts and metadata.
type DocumentParserServiceServer interface {
	// Parse accepts a stream of binary chunks from a document, and returns
	// the extracted metadata and markdown text chunks asynchronously.
	// Using client streaming to avoid hitting gRPC maximum message size (4MB limit).
	// Using server streaming to handle large parsed outputs incrementally.
	Parse(grpc.BidiStreamingServer[ParseRequest, ParseResponse]) error
	mustEmbedUnimplementedDocumentParserServiceServer()
}

// UnimplementedDocumentParserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentParserServiceServer struct{}

func (UnimplementedDocumentParserServiceServer) Parse(grpc.BidiStreamingServer[ParseRequest, ParseResponse]) error {
	return status.Error(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedDocumentParserServiceServer) mustEmbedUnimplementedDocumentParserServiceServer() {}
func (UnimplementedDocumentParserServiceServer) testEmbeddedByValue()                               {}

// UnsafeDocumentParserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentParserServiceServer will
// result in compilation errors.
type UnsafeDocumentParserServiceServer interface {
	mustEmbedUnimplementedDocumentParserServiceServer()
}

func RegisterDocumentParserServiceServer(s grpc.ServiceRegistrar, srv DocumentParserServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentParserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentParserService_ServiceDesc, srv)
}

func _DocumentParserService_Parse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentParserServiceServer).Parse(&grpc.GenericServerStream[ParseRequest, ParseResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentParserService_ParseServer = grpc.BidiStreamingServer[ParseRequest, ParseResponse]

// DocumentParserService_ServiceDesc is the grpc.ServiceDesc for DocumentParserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentParserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booksage.v1.DocumentParserService",
	HandlerType: (*DocumentParserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Parse",
			Handler:       _DocumentParserService_Parse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "booksage/v1/booksage.proto",
}

const (
	EmbeddingService_GenerateEmbeddings_FullMethodName = "/booksage.v1.EmbeddingService/GenerateEmbeddings"
)

// EmbeddingServiceClient is the client API for EmbeddingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmbeddingService handles text embedding operations.
type EmbeddingServiceClient interface {
	// GenerateEmbeddings accepts batches of text and returns their vector representations.
	GenerateEmbeddings(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
}

type embeddingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbeddingServiceClient(cc grpc.ClientConnInterface) EmbeddingServiceClient {
	return &embeddingServiceClient{cc}
}

func (c *embeddingServiceClient) GenerateEmbeddings(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, EmbeddingService_GenerateEmbeddings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbeddingServiceServer is the server API for EmbeddingService service.
// All implementations must embed UnimplementedEmbeddingServiceServer
// for forward compatibility.
//
// EmbeddingService handles text embedding operations.
type EmbeddingServiceServer interface {
	// GenerateEmbeddings accepts batches of text and returns their vector representations.
	GenerateEmbeddings(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	mustEmbedUnimplementedEmbeddingServiceServer()
}

// UnimplementedEmbeddingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmbeddingServiceServer struct{}

func (UnimplementedEmbeddingServiceServer) GenerateEmbeddings(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateEmbeddings not implemented")
}
func (UnimplementedEmbeddingServiceServer) mustEmbedUnimplementedEmbeddingServiceServer() {}
func (UnimplementedEmbeddingServiceServer) testEmbeddedByValue()                          {}

// UnsafeEmbeddingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbeddingServiceServer will
// result in compilation errors.
type UnsafeEmbeddingServiceServer interface {
	mustEmbedUnimplementedEmbeddingServiceServer()
}

func RegisterEmbeddingServiceServer(s grpc.ServiceRegistrar, srv EmbeddingServiceServer) {
	// If the following call panics, it indicates UnimplementedEmbeddingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmbeddingService_ServiceDesc, srv)
}

func _EmbeddingService_GenerateEmbeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbeddingServiceServer).GenerateEmbeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmbeddingService_GenerateEmbeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbeddingServiceServer).GenerateEmbeddings(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmbeddingService_ServiceDesc is the grpc.ServiceDesc for EmbeddingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmbeddingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booksage.v1.EmbeddingService",
	HandlerType: (*EmbeddingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateEmbeddings",
			Handler:    _EmbeddingService_GenerateEmbeddings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booksage/v1/booksage.proto",
}
